@extends('app')
@section('content')
@include('partials.page_top_navigation')
<div class="clearfix"></div>
<div class="main">
    <div class="container">
        
        
           
        
        <div class="col-md-12 landing-page disclaimer-policy">
            <div class="less-head">
            <div>
                <h3>DISCLAIMER</h3>
                
                <h6>DISCLAIMER:  USER</h6>
                        <p>When you are availing the services on or of this Platform, as a “Buyer”, you are agreeing, on your behalf and on behalf of anyone else with an interest in the shipment/ delivery/ transfer, that the Termsfor the Buyer shall apply to you.<br><br>
                            The version of this Platform is merely for the purposes of soft launch, meant mainly for testing the functionality and test/tweak design of the Platform. Thus, allowing any adjustments or subsequent changes made to increase the functionality. We make no warranties or representations about the accuracy or completeness of this Platform and contents hereof as they are subject to change. We nor any of Our Seller, contractors, directors or employees shall be liable for any direct, incidental, consequential, indirect or punitive damages arising out of access to or use of any content of this Platform. Additionally, we make no representation that the operation of the Platform will be uninterrupted or error-free, and we will not be liable for the consequences of any interruptions or errors.<br><br>
                        We communicate information provided and created by content partners, software developers, publishers, marketing agents, employees, Buyers, resellers, advertisers and other third parties. While every attempt has been made to ascertain the authenticity and validity of the content on the Platforms, We have no control over content, the accuracy of such content, integrity or quality of such content and the information on Our pages, and material on the Platforms may include technical inaccuracies or typographical errors, and We make no guarantees, nor can We be responsible for any such information, including its authenticity, currency, content, quality, copyright compliance or legality, or any other intellectual property rights compliance, or any resulting loss or damage. We hereby make no express or implied warranties or representations with respect to the Platform or any services advertised, sold or provided through the Platform (including inter alia representations and warranties relating to timely delivery, quality of services, completion of service, authority and capability of the Seller providing the services, non-infringement or non-violation of applicable laws for such services, or any implied warranties arising out of a course of performance, dealing, or trade usage).<br><br>
                        FURTHER, WE ARE NOT LIABLE FOR ANY KIND OF DAMAGES, LOSSES OR ACTION ARISING DIRECTLY OR INDIRECTLY DUE TO USAGE OF THE PLATFORM, THE SERVCIES OF THE SELLER, ANY CONTENT, INCLUDING ANY ERRORS OR OMISSIONS IN ANY CONTENT, ACCESS AND/OR USE OF THE CONTENT ON THE PLATFORM OR ANY OF THEM INCLUDING BUT NOT LIMITED TO CONTENT BASED DECISIONS RESULTING IN LOSS OF DATA, REVENUE, PROFITS, PROPERTY, INFECTION BY VIRUSES, DISTRIBUTED DENIAL-OF-SERVICE ATTACK, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF OUR PLATFORM OR TO YOUR DOWNLOADING OF ANY CONTENT ON IT, OR ON ANY WEBSITE LINKED TO IT ANY TECHNOLOGY FAILURE SUCH AS SLOW WORKING OF PLATFORM, SITE CRASHES, UPTIME, DOWNTIME, FAILURE OF PAYMENT GATEWAYS, CALL CENTER SERVICES, ETC.</p>
                        
                        <h6>DISCLAIMER: BUYER</h6>
                        <p>The version of this Platform is merely for the purposes of soft launch, meant mainly for testing the functionality and test/tweak design of the Platform. Thus, allowing any adjustments or subsequent changes made to increase the functionality. We make no warranties or representations about the accuracy or completeness of this Platform and contents hereof as they are subject to change. We nor any of Our User, directors, contractors or employees shall be liable for any direct, incidental, consequential, indirect or punitive damages arising out of access to or use of any content of this Platform.Additionally, we make no representation that the operation of the Platform will be uninterrupted or error-free, and we will not be liable for the consequences of any interruptions or errors.<br><br>
                        We communicate information provided and created by content partners, software developers, publishers, marketing agents, employees, users, resellers, advertisers and other third parties. While every attempt has been made to ascertain the authenticity and validity of the content on the Platforms, We have no control over content, the accuracy of such content, integrity or quality of such content and the information on Our pages, and material on the Platforms may include technical inaccuracies or typographical errors, and We make no guarantees, nor can We be responsible for any such information, including its authenticity, currency, content, quality, copyright compliance or legality, or any other intellectual property rights compliance, or any resulting loss or damage. We hereby make no express or implied warranties or representations with respect to the Platform or any services herein including any purchaser of the services offered by you through the Platform (including inter alia representations and warranties relating to timely payment, authority and capability of the User availing the services, non-infringement or non-violation of applicable laws by the User while availing the services, or any implied warranties arising out of a course of performance, dealing, or trade usage).<br><br>
                        FURTHER, WE ARE NOT LIABLE FOR ANY KIND OF DAMAGES, LOSSES OR ACTION ARISING DIRECTLY OR INDIRECTLY DUE TO USAGE OF THE PLATFORM, ANY CONTENT, INCLUDING ANY ERRORS OR OMISSIONS IN ANY CONTENT, ACCESS AND/OR USE OF THE CONTENT ON THE PLATFORM OR ANY OF THEM INCLUDING BUT NOT LIMITED TO CONTENT BASED DECISIONS RESULTING IN LOSS OF DATA, REVENUE, PROFITS, PROPERTY, INFECTION BY VIRUSES, DISTRIBUTED DENIAL-OF-SERVICE ATTACK, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF OUR PLATFORM OR TO YOUR DOWNLOADING OF ANY CONTENT ON IT, OR ON ANY WEBSITE LINKED TO IT, ANY TECHNOLOGY FAILURE SUCH AS SLOW WORKING OF PLATFORM, SITE CRASHES, UPTIME, DOWNTIME, FAILURE OF PAYMENT GATEWAYS, CALL CENTER SERVICES, ETC.</p>
                        
            </div>
            </div>
       </div>
    </div>
    <div class="clearfix"></div>
    @include('partials.footer')	
</div>	
@endsection
